services:
    # CQRS - Configuration manuelle des middlewares
    App\Application\Shared\CQRS\Middleware\CommandLoggingMiddleware:
        tags: [ "app.cqrs.command_middleware" ]

    App\Application\Shared\CQRS\Middleware\QueryLoggingMiddleware:
        tags: [ "app.cqrs.query_middleware" ]

    App\Application\Shared\CQRS\Middleware\QueryCacheMiddleware:
        tags:
            - { name: "app.cqrs.query_middleware", priority: -100 }
