
services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: en_shop_api_database
    restart: always
    build:
        context: ./docker/database
        dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  ###> symfony/messenger with rabbitmq ###
  rabbitmq:
    container_name: en_shop_api_rabbitmq
    build:
      context: ./docker/rabbitmq
      dockerfile: ./Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  ###< symfony/messenger with rabbitmq ###

  varnish:
    container_name: en_shop_api_varnish
    build:
      context: ./docker/varnish
      dockerfile: ./Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/varnish/conf:/etc/varnish:ro

  redis:
    container_name: en_shop_api_redis
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  ###> symfony/messenger with rabbitmq ###
  rabbitmq_data:
  ###< symfony/messenger with rabbitmq ###
  redis_data:
