
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "20902:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "20906:1025"
      - "20907:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/messenger with rabbitmq ###
  rabbitmq:
    ports:
      - "20908:5672"   # AMQP protocol
      - "20909:15672" # Management UI
###< symfony/messenger with rabbitmq ###

  varnish:
    ports:
      - "20901:80"
